#!/bin/bash
cat $1 | sglri -p src/grammar/PHP5.tbl | typing_printer
cat $1 | sglri -p src/grammar/PHP5.tbl | typing_debugger
cat $1 | sglri -p src/grammar/PHP5.tbl | typing_visualizer | dot -Tpng > tree.png
cat $1 | sglri -p src/grammar/PHP5.tbl | typing_inferencer

#cat tree.dot | dot -Tpng > tree.png
